[2024-09-15T22:49:46.637+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-15T22:49:46.660+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: holtzy_etl.load_data manual__2024-09-15T22:49:35.017772+00:00 [queued]>
[2024-09-15T22:49:46.808+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: holtzy_etl.load_data manual__2024-09-15T22:49:35.017772+00:00 [queued]>
[2024-09-15T22:49:46.810+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-09-15T22:49:46.825+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-09-15 22:49:35.017772+00:00
[2024-09-15T22:49:46.832+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=226) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-15T22:49:46.834+0000] {standard_task_runner.py:63} INFO - Started process 228 to run task
[2024-09-15T22:49:46.834+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'holtzy_etl', 'load_data', 'manual__2024-09-15T22:49:35.017772+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpbd3q2t4r']
[2024-09-15T22:49:46.836+0000] {standard_task_runner.py:91} INFO - Job 98: Subtask load_data
[2024-09-15T22:49:46.883+0000] {task_command.py:426} INFO - Running <TaskInstance: holtzy_etl.load_data manual__2024-09-15T22:49:35.017772+00:00 [running]> on host 554250d17fb3
[2024-09-15T22:49:46.973+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fabriciositto' AIRFLOW_CTX_DAG_ID='holtzy_etl' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-09-15T22:49:35.017772+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-15T22:49:35.017772+00:00'
[2024-09-15T22:49:46.974+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-15T22:49:46.997+0000] {logging_mixin.py:188} INFO - Engine is created and ready to use.
[2024-09-15T22:49:46.998+0000] {logging_mixin.py:188} INFO - The upload could not be completed - module 'modules.connect_db' has no attribute 'connect'
[2024-09-15T22:49:46.999+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-15T22:49:47.000+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-15T22:49:47.012+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=holtzy_etl, task_id=load_data, run_id=manual__2024-09-15T22:49:35.017772+00:00, execution_date=20240915T224935, start_date=20240915T224946, end_date=20240915T224947
[2024-09-15T22:49:47.050+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-15T22:49:47.066+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15T22:49:47.069+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
